### ISSUE TITLE
Plugin help display bugs

### ISSUE THREAD

**Issue by pgmann** [zDevelopers/zLib#11]
- [ ] The section sign works as expected but coloured chat looks like this (example screenshot, from SpectatorPlus). Note the `A` with the circle on top, I don't even know what it's called!
  ![image](https://cloud.githubusercontent.com/assets/5852501/15583749/10f72d32-236f-11e6-8952-de73344bd15b.png)
- [x] Subcommand help has each line prefixed with `|` while the main command help does not have this. It would be nice to see the main command include this too.

**Comment by AmauryCarrade** [comment]
Is the first point still a thing?
(By the way, the “A with the circle on top” is an Â (a-circumflex).)

I agree on your second point, this is not really coherent.

**Comment by AmauryCarrade** [comment]
Closed as the commands help was redesigned (with these suggestions in mind) and the encoding issue never reproduced. :)
