### ISSUE TITLE
Maven Repository

### ISSUE THREAD

**Issue by TheDodo24** [zDevelopers/zLib#18]
The maven repository is down, can you fix it?

**Comment by AmauryCarrade** [comment]
Indeed. I'll reboot that in the afternoon. :)

**Comment by TheDodo24** [comment]
The repository is still offline

**Comment by AmauryCarrade** [comment]
I had no time this afternoon after all, sorry. I'm investigating the problem right now, still trying to understand why it crashes at startup.

**Comment by AmauryCarrade** [comment]
The Maven server is back! (and upgraded in the meantime)

Sorry for the inconvenience and thanks for your patience (and for using zLib) :slightly_smiling_face:

**Comment by TheDodo24** [comment]
no problem ;)
