### ISSUE TITLE
zLib, qu'est ce que c'est ?

### ISSUE THREAD

**Issue by YoLaw** [zDevelopers/zLib#4]
Bonjour,
j'actualise 2 fois par jour la page Jenkins pour les snapshots de UHPlugin, et je vois que depuis un certain temps, le build "zlib" est apparu... En plus de ça, les builds de UHPlugin ne sont modifiés que dans les dépendances".
Qu'est ce donc que zLib et à quoi sert t'il? Quel changements apporte t'il à UHPlugin?
Merci ! :)

**Comment by AmauryCarrade** [comment]
zLib est un outil pour développeurs auquel j'ai contribué, et qui sert à centraliser en un projet utilisé par d'autres diverses fonctionnalités utiles dans les plugins Bukkit mais qui manquent dans l'API.

Par exemple, la *sidebar* d'UHCr est gérée via un composant de la zLib, ce qui lui permet d'être traitée de manière asynchrone (sans ralentir le jeu) et d'être unique pour chaque joueur.
Certains messages JSON (style /tellraw) sont également envoyés via un utilitaire présent dans la zLib. Etc.
D'autres outils vont être utilisés également : titres, action bar, GUI peut-être...

Pour l'utilisateur, ça ne change rien.

**Comment by YoLaw** [comment]
Ah d'accord! :) Donc en gros ça vous ouvrir des nouvelles fonctionnalités, et faites plus simplement?

**Comment by AmauryCarrade** [comment]
Oui, et surtout sans les réécrire sur chaque projet. Elles sont implémentées et testées une fois ici, et utilisées directement ensuite. On gagne du temps, et c'est plus pratique :) .

**Comment by YoLaw** [comment]
Super cool! Hate de voir quand tout ça sera fini! :D

**Comment by YoLaw** [comment]
Petite question: zLib peut il êtreutilisé par d'autres développeurs pour créer d'autres plugins?

**Comment by AmauryCarrade** [comment]
Tout à fait, libre à quiconque qui veut l'utiliser de le faire :) .

**Comment by YoLaw** [comment]
Super merci! :)
