### ISSUE TITLE
zLib javadoc not displaying

### ISSUE THREAD

**Issue by pgmann** [zDevelopers/zLib#9]
At the current point in time the only way to find any documentation about this project is to build it yourself.

The reason Javadoc doesn't display on Jenkins is that Jenkins sets a very restrictive `sandbox` in  the `Content-Security-Policy` header. You can either unset this in the Apache proxy or set your own header instead ([which I did](https://ci.pgmann.cf/job/SpectatorPlus/javadoc/)).

You likely already know how to set a header in Apache:
```
Header [un]set Content-Security-Policy <value>
```

**Comment by AmauryCarrade** [comment]
Thanks for reporting; fixed now :) .
